### ISSUE TITLE
SetInsertMarkPosition during DragMouseMove with groups

### ISSUE THREAD

**Issue by dejo1001** [TimoKunze/ExplorerListView#1]
Attempting to drag a row in a listview with groups results in run-time error 0x80004005: Method SetInsertMarkPosition of object IExplorerListView failed.
If the groups are disabled, it works fine.

**Comment by TimoKunze** [comment]
The reason is this:

> An insertion point can only appear if the list-view control is in icon view, small icon view, or tile view, and is not in group-view mode.

https://learn.microsoft.com/en-us/windows/win32/controls/lvm-setinsertmark

So the Windows native listview control simply does not support it.

**Comment by dejo1001** [comment]
You are right. I didn't think to check the MSDN.
